#include <bits/stdc++.h>
using namespace std;

/*
Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of elements from the array.
Note: AND is bitwise '&' operator.
*/
int maxBitwiseANDValue(vector<int> &v) {
    int maxVal=*max_element(v.begin(),v.end());
	    int cntBits=0;
	    while(maxVal){
	        cntBits++;
	        maxVal >>= 1;
	    }
	    int maxAndVal=0;
	    while(cntBits>=0){
	        maxAndVal |= (1<<cntBits);
	        
	        int cntValues=0;
	        for(int i=0;i<v.size();i++){
	            if((v[i] & maxAndVal) == maxAndVal)
	              cntValues++;
	        }
	        if(cntValues < 2){
	          maxAndVal &= ~(1<<cntBits);
	        }
	        cntBits--;
	    }
	    return maxAndVal;
}

int main() {
    vector<int> v={2,12,8,16};
    cout<<maxBitwiseANDValue(v);
}